// Sound for the narrated Product Hunt film: the chosen bed (measured with bin/beats.mjs, music.json), ducked under
// the voice, and soft effects on the animation moments (voice anchors from vo.json). Writes audio.json.
import fs from 'node:fs';
import path from 'node:path';

const dir = path.dirname(new URL(import.meta.url).pathname);
const VO = JSON.parse(fs.readFileSync(path.join(dir, 'vo.json'), 'utf8'));
const LN = Object.fromEntries(VO.lines.map((l) => [l.id, l]));
const W = (id, i = 0) => LN[id].words[i].s, S = (id) => LN[id].start, END = (id) => LN[id].end;
const r = (x) => +x.toFixed(3);
const PROMPT = 'Light, upbeat and optimistic tech explainer music at exactly 100 BPM: plucky synths, soft claps, a warm bouncing bass, gentle marimba and bright bell accents; friendly, modern and steady, made to sit under a narrator. No vocals, no breaks, no long silences, no big final hit. A steady, feel-good groove from the first second with small lifts every eight bars, slightly brighter from about 28 seconds, and a soft, clean ending in the last 4 seconds.';

const cues = {
  spark: [0.3],
  land: [1.25],
  bloom: [W('build', 1)],
  fill: [W('build', 2) + 0.15],
  love: [W('build', 5)],
  days: [W('tell', 1) - 0.1],
  msgs: [W('tell', 3), W('tell', 3) + 0.5],
  push: [END('tell') - 0.3],
  launch: [S('path') - 0.15],
  slam: [W('path', 4) - 0.05, W('path', 7) - 0.05, W('path', 11) - 0.05],
  hop: [W('path', 7) - 0.55, W('path', 11) - 0.55, W('lost', 1), W('lost', 3), W('lost', 5), W('lost', 8)],
  chip: [W('path', 7), W('path', 11), W('lost', 3), W('lost', 10)],
  snap: [W('lost', 10)],
  fall: [W('lost', 10) + 0.3],
  dust: [W('cost', 1)],
  repeat: [W('cost', 2), W('cost', 2) + 0.35, W('cost', 2) + 0.7],
  rewind: [W('whatif', 0) - 0.1],
  whole: [W('whatif', 5) + 0.15],
  draw: [W('whatif', 6) - 0.1],
  gather: [S('that') - 0.1],
  reveal: [W('that', 1) - 0.05],
  pop: [W('what', 0), W('what', 1), W('what', 2), W('what', 3), W('what', 5)],
  frame: [W('what', 9) - 0.15],
  swirl: [W('what', 11)],
  thread: [W('what', 14)],
  track: [S('echo') - 0.3],
  ping: [W('echo', 4) - 0.3, W('echo', 7) - 0.3],
  move: [W('bug', 7) - 0.6, W('fix', 0) - 0.6, W('fix', 4) - 0.6, W('fix', 7) - 0.6, W('back', 0) - 0.6],
  bug: [W('bug', 3) - 0.05],
  found: [W('bug', 8)],
  type: [W('fix', 1), W('back', 2)],
  scan: [W('fix', 5) - 0.1],
  check: [W('fix', 5) + 0.15, W('fix', 5) + 0.3, W('fix', 5) + 0.45],
  stamp: [W('fix', 8) - 0.05],
  loop: [W('back', 5)],
  done: [W('back', 12)],
  decide: [W('control', 1)],
  toggle: [W('control', 10)],
  bars: [S('work') - 0.3],
  strike: [W('work', 11) + 0.35],
  brackets: [W('oss', 2) - 0.1],
  typing: [W('oss', 4)],
  rings: [S('tagline') - 0.3],
  scatter: [S('cta')],
  converge: [W('cta', 7)],
  onePlace: [W('cta', 11)],
  lockup: [END('cta') + 0.1],
};
const sounds = {
  scatter: { text: 'a jittery flurry of small glitchy digital blips, scattered and disorganised, soft', duration: 1.5, gain: -23 },
  converge: { text: 'many soft whooshes pulling inward to one point, rising', duration: 1.1, gain: -18 },
  onePlace: { text: 'a bright soft shimmer impact with a warm bloom, pieces locking together into one', duration: 1.5, gain: -15 },
  land: { text: 'a small soft thud with a sparkly scatter, a tiny ring landing and bursting into confetti', duration: 1.0, gain: -18 },
  fill: { text: 'a quick bright liquid fill swoosh, left to right', duration: 0.6, gain: -21 },
  love: { text: 'a bright happy sparkle burst with a soft pop', duration: 1.0, gain: -18 },
  days: { text: 'seven tiny ascending blips, quick', duration: 1.0, gain: -22 },
  push: { text: 'a fast rising whoosh, a camera zooming in', duration: 0.8, gain: -19 },
  launch: { text: 'a rocket-like soft whoosh launching upward with a glowing trail', duration: 1.0, gain: -17 },
  slam: { text: 'a punchy soft thump as a bold word slams in', duration: 0.5, gain: -18 },
  snap: { text: 'a light crack of lines snapping', duration: 0.5, gain: -20 },
  fall: { text: 'letters tumbling and falling, light plastic clatter', duration: 0.8, gain: -21 },
  whole: { text: 'a bright satisfying click as pieces lock back together, with a shimmer', duration: 0.8, gain: -18 },
  gather: { text: 'a quick inward suck whoosh', duration: 0.5, gain: -20 },
  swirl: { text: 'several soft whooshes swirling around in a circle', duration: 1.2, gain: -20 },
  thread: { text: 'a soft electric shimmer, lines connecting', duration: 1.0, gain: -22 },
  bug: { text: 'a quick glitchy error blip', duration: 0.5, gain: -18 },
  check: { text: 'soft bright check-mark ding', duration: 0.5, gain: -21 },
  stamp: { text: 'a satisfying rubber stamp thump', duration: 0.5, gain: -16 },
  decide: { text: 'a punchy soft thump as a bold word slams in', duration: 0.5, gain: -19 },
  strike: { text: 'a quick marker strike-through swish', duration: 0.5, gain: -20 },
  typing: { text: 'soft fast typing on a keyboard for a second', duration: 1.2, gain: -22 },
  spark: { text: 'a tiny bright sparkle, a point of light appearing', duration: 0.6, gain: -20 },
  bloom: { text: 'a soft warm bloom swell, light growing', duration: 1.0, gain: -19 },
  msgs: { text: 'several soft chat message pops swirling in', duration: 1.2, gain: -21 },
  hop: { text: 'a light airy whoosh, a glowing block hopping across', duration: 0.5, gain: -21 },
  chip: { text: 'small glassy pieces chipping off and falling, light crackle', duration: 0.8, gain: -20 },
  dust: { text: 'a soft sandy dissolve, pieces turning to dust', duration: 1.2, gain: -21 },
  repeat: { text: 'a soft chat message pop', duration: 0.5, gain: -22 },
  rewind: { text: 'a smooth reverse swoosh, pieces flying back together', duration: 1.0, gain: -18 },
  draw: { text: 'a smooth soft line drawing swish', duration: 1.0, gain: -22 },
  reveal: { text: 'a bright soft shimmer impact with a warm bloom, a logo revealed, gentle', duration: 1.5, gain: -16 },
  pop: { text: 'a soft bubbly UI pop', duration: 0.5, gain: -22 },
  frame: { text: 'a smooth soft snap, a frame closing around things', duration: 0.5, gain: -21 },
  orbit: { text: 'a soft rising orbit whoosh', duration: 1.0, gain: -21 },
  track: { text: 'a soft digital line drawing across, gentle', duration: 0.8, gain: -22 },
  ping: { text: 'a soft digital ping', duration: 0.5, gain: -22 },
  move: { text: 'a light airy whoosh, a glowing block gliding along a track', duration: 0.5, gain: -22 },
  found: { text: 'three tiny soft blips', duration: 0.5, gain: -22 },
  scan: { text: 'a soft electronic scan sweep', duration: 0.8, gain: -21 },
  approve: { text: 'a soft click and a warm confirmation tone', duration: 0.8, gain: -18 },
  loop: { text: 'a smooth flowing whoosh travelling around a loop', duration: 1.5, gain: -21 },
  done: { text: 'short warm two-note success chime, soft', duration: 0.8, gain: -18 },
  toggle: { text: 'a smooth toggle switch sliding with a soft click', duration: 0.5, gain: -19 },
  bars: { text: 'a soft rising shimmer of many small tones', duration: 1.0, gain: -22 },
  brackets: { text: 'a smooth pen stroke drawing two brackets, soft', duration: 0.6, gain: -21 },
  type: { text: 'soft fast typing on a keyboard for a second', duration: 1.2, gain: -22 },
  rings: { text: 'a soft airy shimmer, rings of light expanding', duration: 1.2, gain: -20 },
  lockup: { text: 'a single warm soft bell tone with a gentle tail', duration: 1.8, gain: -17 },
};
const audio = {
  name: 'ph-story',
  duration: VO.total,
  video: '../../out/ph-story/ph-story.mp4',
  master: { lufs: -14, fadeOut: 1.5 },
  voice: { from: 'vo.json', gain: 0, duck: { threshold: 0.03, ratio: 6, attack: 20, release: 400, sfx: false } },
  music: [{ at: 0, length: VO.total, generate: 82, from: 0, gain: -6, fadeIn: 0.05, fadeOut: 2.0, prompt: PROMPT }],
  sounds,
  cues: Object.entries(cues).map(([sound, at]) => ({ sound, at: at.map(r) })),
};
fs.writeFileSync(path.join(dir, 'audio.json'), JSON.stringify(audio, null, 1));
console.log(`audio.json: ${Object.keys(sounds).length} sounds, ${Object.values(cues).flat().length} cues`);
